#ifndef COMMON_DECLARATIONS_H
#define COMMON_DECLARATIONS_H

#define MODEL_FORMAT_VERSION_NUMBER 6
#define RIGID_ANIMATION_FORMAT_VERSION_NUMBER 0
#define SKELETAL_ANIMATION_FORMAT_VERSION_NUMBER 1
#define ARMATURE_FORMAT_VERSION_NUMBER 1

#endif // COMMON_DECLARATIONS_H
