#ifndef COMMON_DECLARATIONS_H
#define COMMON_DECLARATIONS_H

#define MODEL_FORMAT_VERSION_NUMBER 6
#define ANIMATION_FORMAT_VERSION_NUMBER 0
#define ARMATURE_FORMAT_VERSION_NUMBER 0

#endif // COMMON_DECLARATIONS_H
